name: "Entrée de journal"
description: "Documenter une étape de travail (contrat, code, test)"
title: "Journal (auto-renamed by workflow)"
labels: ["journal"]

body:
  - type: textarea
    id: objectif
    attributes:
      label: Objectif
      description: "Quel résultat on vise pour cette entrée."
      placeholder: "Ex: Implémenter mqtt/client.js et ses tests (Vitest + broker aedes)"
    validations:
      required: true

  - type: textarea
    id: contexte
    attributes:
      label: Contexte
      description: "Pourquoi cette étape ? Lien avec journaux précédents, risques/planning."
      placeholder: "Ex: Journal #001 a défini les contrats ; ici on dé-risque l'I/O MQTT"
    validations:
      required: false

  - type: textarea
    id: decisions
    attributes:
      label: Décisions
      description: "Décisions clés prises pour cette entrée."
      placeholder: "- Utiliser mqtt.js v4\n- Promises pour subscribe/publish\n- LWT optionnelle"
    validations:
      required: true

  - type: textarea
    id: portee
    attributes:
      label: Portée (Scope / Done)
      description: "Ce qui est couvert par cette entrée."
      placeholder: "- Wrapper mqtt/client.js (connect/subscribe/publish/close)\n- Tests intégration avec aedes\n- QoS par défaut = 1"
    validations:
      required: false

  - type: textarea
    id: hors_portee
    attributes:
      label: Hors Portée (Out of scope)
      description: "Ce qui n'est PAS couvert ici et sera traité plus tard."
      placeholder: "- Backoff exponentiel\n- Intégration ingestion DB\n- Filtrage par pattern de topic"
    validations:
      required: false

  - type: textarea
    id: artefacts
    attributes:
      label: Artifacts produits
      description: "Docs, schémas, interfaces, fichiers ajoutés."
      placeholder: "- service-app/src/mqtt/client.js\n- service-app/test/mqtt.client.test.js\n- docs/journal/YYYY-MM-DD-entree-XXX.md"
    validations:
      required: false

  - type: textarea
    id: liens
    attributes:
      label: Liens utiles
      description: "Liens vers journaux, contrats, PR, Notion."
      placeholder: "- Journal #001 …\n- Contrat service-app …\n- PR: …"
    validations:
      required: false

  - type: textarea
    id: plan
    attributes:
      label: Plan d’implémentation
      description: "Étapes prévues pour livrer ce journal."
      placeholder: "1) Installer deps\n2) Implémenter client.js\n3) Écrire tests\n4) Lancer CI"
    validations:
      required: false

  - type: textarea
    id: commands
    attributes:
      label: Commandes exécutées (optionnel)
      placeholder: "npm i mqtt\nnpm i -D vitest aedes\nnpm run test"
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Critères d’acceptation
      description: "Conditions de réussite vérifiables."
      placeholder: "- Tous les tests passent (Vitest)\n- API du wrapper conforme au contrat\n- Fermeture clean sans fuite de sockets"
    validations:
      required: true

  - type: textarea
    id: risques
    attributes:
      label: Risques & mitigations
      placeholder: "- Ports occupés → port dynamique\n- Fuites sockets → always await close()"
    validations:
      required: false

  - type: textarea
    id: todo
    attributes:
      label: Suivi / TODO
      placeholder: "- Ajouter helper onTopic(pattern)\n- Ajouter test retain/LWT"
    validations:
      required: false

  - type: textarea
    id: dod
    attributes:
      label: Definition of Done (DoD)
      description: "Définition de fait : quand considère-t-on que c'est terminé ?"
      placeholder: "- Code mergé dans develop via PR\n- CI verte\n- Journal commité & lié à l’issue"
    validations:
      required: false
